### ISSUE TITLE
Docker image doesn't exist

### ISSUE THREAD

**Issue by tyilo** [tofuutils/pre-commit-opentofu#4]
### Describe the bug

The docker image can't be pulled.

### How can we reproduce it?

```
$ docker pull ghcr.io/tofuutils/pre-commit-opentofu
Using default tag: latest
Error response from daemon: Head "https://ghcr.io/v2/tofuutils/pre-commit-opentofu/manifests/latest": unauthorized
```

**Comment by kvendingoldo** [comment]
will fix it soon, thank you for reporting

**Comment by kvendingoldo** [comment]
I pulled it without issues. @tyilo are you logged in to ghcr.io via docker login?

**Comment by kvendingoldo** [comment]
Hmm. Did it without login:

```
docker pull ghcr.io/tofuutils/pre-commit-opentofu:nightly
nightly: Pulling from tofuutils/pre-commit-opentofu
1207c741d8c9: Already exists
a3c7bc1de874: Already exists
18dfb1d5a53f: Already exists
813fee53afe1: Already exists
bc33fb833569: Already exists
9a5fbe01485f: Downloading [================================>                  ]  40.01MB/62.24MB
b3db596df9f2: Downloading [===========>                                       ]  50.27MB/220.8MB
7eb8cc10e442: Downloading [=============================>                     ]  47.58MB/80.38MB
066fa47bcd5d: Waiting
13a9501ec55e: Waiting
28a9603b6c9d: Waiting
````

can you share logs, pls?

**Comment by tyilo** [comment]
I can neither pull the `latest` nor the `nightly` tag. I have tried this on multiple machines.

I can pull other images from ghcr.io fine.

Are the docker images public?

**Comment by kvendingoldo** [comment]
@tyilo can you try to pull it from dockerhub, please?
https://hub.docker.com/repository/docker/tofuutils/pre-commit-opentofu/tags

**Comment by tyilo** [comment]
> @tyilo can you try to pull it from dockerhub, please? https://hub.docker.com/repository/docker/tofuutils/pre-commit-opentofu/tags

That works :)

**Comment by tyilo** [comment]
@kvendingoldo I think you should reopen this issue until the README references a working docker URL.

**Comment by kvendingoldo** [comment]
@tyilo updated readme.md

**Comment by tyilo** [comment]
Thanks, but there is still 4 references to ghcr.io in the README.

**Comment by kvendingoldo** [comment]
@tyilo sorry, missed them. Fixed :)
